name: uber_eats_consumer
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.2.6+12

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4
  cloud_firestore: ^3.4.5
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.6
  flutter_local_notifications: ^9.9.1
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  url_launcher: ^6.1.5
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  uuid: ^3.0.6
  video_thumbnail: ^0.5.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  video_player: ^2.4.2
  flutter_facebook_auth: ^4.3.4
  http: ^0.13.5
  smooth_page_indicator: ^1.0.0+2
  firebase_messaging: ^12.0.3
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.4.0
  permission_handler: ^6.0.1+1
  easy_localization: ^3.0.2-dev
  mime: ^1.0.2
  moor_flutter: ^4.1.0
  path: ^1.8.1
  font_awesome_flutter: ^10.1.0
  flutter_polyline_points: ^1.0.0
  percent_indicator: ^4.2.2
  lottie: ^1.4.1
  flutter_native_image: ^0.0.6+1
  video_compress: ^3.1.1
  flutter_sound: ^8.3.9
  the_apple_sign_in: ^1.1.1
  cupertino_icons: ^1.0.5
  dotted_border: ^2.0.0+2
  rename: ^2.0.1
  flutter_braintree:
  flutter_staggered_animations: ^1.0.0
  flutter_rating_bar: ^4.0.1
  place_picker: ^0.9.19
  google_maps_flutter: any
  geolocator: ^7.0.1
  geocoding: ^2.0.4
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.4.1
  clipboard: ^0.1.3
  geoflutterfire: ^3.0.3
  razorpay_flutter:
  platform:
  location:
  flutter_stripe: ^3.0.2
  paytm_allinonesdk: ^1.1.7
  webview_flutter: ^3.0.4
  flutterwave_standard: ^1.0.3
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: ^1.1.0
  flutter_facebook_keyhash: ^0.0.4
  firebase_crashlytics: ^2.8.3
  flutter_qr_bar_scanner: ^3.0.2
  mercadopago_sdk: ^1.3.0
  #  mpcheckout: ^0.0.5
  bloc:
  flutter_bloc:



dev_dependencies:
  moor_generator: ^4.6.0+1
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/ic_launcher-playstore.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/flags/
    - assets/json file/
    - assets/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
